spring:
  datasource:
    url: jdbc:mysql://localhost:3307/restaurant_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  servlet:
    context-path: /api
redis:
  host: localhost
  port: 6379
